ALTER TABLE "UserTrainingPlan" ADD COLUMN IF NOT EXISTS "age" INTEGER;
ALTER TABLE "UserTrainingPlan" ADD COLUMN IF NOT EXISTS "fitnessLevel" TEXT;
ALTER TABLE "UserTrainingPlan" ADD COLUMN IF NOT EXISTS "goalRaceDate" TIMESTAMP(3);
